basePath: /
definitions:
  handler.AddCertificateRequest:
    properties:
      url:
        type: string
    required:
    - url
    type: object
  handler.checkCertificateInfoRequest:
    properties:
      url:
        type: string
    required:
    - url
    type: object
  handler.checkCertificateInfoResponse:
    properties:
      data:
        $ref: '#/definitions/ttlchecker.CertificateInfo'
    type: object
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  handler.getAllCertificatesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/ttlchecker.CertificateResponse'
        type: array
    type: object
  handler.getCertificateResponse:
    properties:
      data:
        $ref: '#/definitions/ttlchecker.CertificateResponse'
    type: object
  ttlchecker.CertificateInfo:
    properties:
      days_left:
        type: integer
      url:
        type: string
      valid_from:
        type: string
      valid_to:
        type: string
    type: object
  ttlchecker.CertificateResponse:
    properties:
      days_left:
        type: integer
      id:
        type: integer
      url:
        type: string
      user_id:
        type: integer
      valid_from:
        type: string
      valid_to:
        type: string
    type: object
  ttlchecker.User:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8000
info:
  contact:
    email: support@ttl-checker.com
    name: API Support
  description: API для проверки TTL сертификатов
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TTL Checker API
  version: "1.0"
paths:
  /api/certificates:
    get:
      consumes:
      - application/json
      description: Возвращает список сертификатов пользователя
      operationId: get-all-certificates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getAllCertificatesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить все сертификаты
      tags:
      - certificates
  /api/certificates/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет сертификат по ID
      operationId: delete-certificate
      parameters:
      - description: ID сертификата
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Удалить сертификат
      tags:
      - certificates
    get:
      consumes:
      - application/json
      description: Возвращает сертификат по ID
      operationId: get-certificate
      parameters:
      - description: ID сертификата
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getCertificateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить сертификат
      tags:
      - certificates
  /api/certificates/add:
    post:
      consumes:
      - application/json
      description: Добавляет новый сайт для отслеживания SSL сертификата
      operationId: add-certificate
      parameters:
      - description: URL сайта
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.AddCertificateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Добавить сертификат
      tags:
      - certificates
  /api/certificates/check:
    post:
      consumes:
      - application/json
      description: Проверяет срок действия SSL сертификата сайта
      operationId: check-certificate
      parameters:
      - description: URL сайта
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.checkCertificateInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.checkCertificateInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Проверить SSL сертификат
      tags:
      - certificates
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Проверка прав пользователя
      operationId: sign-in
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ttlchecker.User'
      produces:
      - application/json
      responses: {}
      summary: Аутентификация пользователя
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Создание нового пользователя
      operationId: sign-up
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ttlchecker.User'
      produces:
      - application/json
      responses: {}
      summary: Регистрация пользователя
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    description: 'Введите: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
